config:
  heuristic:
    type: moga
    population-size: 40
    new-blocks-generated: 20
    distance-metric: euclidean
    selection:
      mo-selection: domination-rank
      so-selection : tournament
      tournament-size: 4
      tournament-selection-probability: 0.75
      truncation-proportion: 0.3
      maximum-length: 500
  grammar:
    simplicity-bias: 0.6
    plus-node-dist:
      type: geometric
      lower-bound: 1
    star-node-dist:
      type: geometric
      lower-bound: 0
    func-stmts-dist:
      type: geometric
      lower-bound: 0
    func-params-dist:
      type: geometric
      lower-bound: 0
    do-while-stmts-dist:
      type: geometric
      lower-bound: 0
    loop-stmts-dist:
      type: geometric
      lower-bound: 0
    try-block-dist:
      type: geometric
      lower-bound: 0
    catch-block-dist:
      type: geometric
      lower-bound: 0
    catch-block-stmt-dist:
      type: geometric
      lower-bound: 0
    finally-block-dist:
      probability: 0.5
      type: geometric
      lower-bound: 0
    if-block-dist:
      type: geometric
      lower-bound: 0
    else-block-dist:
      # The else block probability is discarded at the moment.
      probability: 1.0
      type: geometric
      lower-bound: 0
  language-features:
    functions:
      enable: true
    expressions:
      simple-expr:
        enable: true
        weight: 1.0
      if-expr:
        enable: true
        weight: 19.0
      elvis-expr:
        enable: true
        weight: 14.0
      try-catch-expr:
        enable: true
        weight: 13.0
    statements:
      simple-stmt:
        enable: true
        weight: 1.0
      do-while-stmt:
        enable: true
        weight: 16.0
      assignment-stmt:
        enable: true
        weight: 18.0
      loop-stmt:
        enable: false
        weight: 1.0
