import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
                    prog='Size and Structure Data Preparation',
                    description='Parse metadata for files passed through the DT pipeline')
    
    parser.add_argument('-f','--files', nargs='+', dest='files',
                        help='The list of absolute paths of files generated by prepare_size_data.py.', required=True)
    args = parser.parse_args()

    dfs = [pd.read_csv(f) for f in args.files]
    df = pd.concat(dfs)

    print(df.dtypes)
    sns.set_theme()
    sns.boxplot(data=df, x="alg_name", y="cummulative")
    plt.savefig('zzz.png')
